#!/usr/bin/env python3
"""Generate the owner-approved M93f trust inputs from pinned NSS certdata.

Run on the host only. Both source arguments must live outside the repository.
The complete source is never copied into the tree; only approved DER and notices
are emitted. See tls/ROOTS-SOURCES.txt for policy, hashes and reproduction.
"""
import hashlib
import re
import sys
from pathlib import Path

REVISION = "940706e6f85676f9d3e65b02d297b16edd788506"
SOURCE_HASH = "beb7e6dfe6499926e52c075c27bcfbe4c957f8609c575b3860273ae2806f63eb"
LICENSE_HASH = "3f3d9e0024b1921b067d6f7f88deb4a60cbe7a78e76c64e3f1d7fc3b779b9d04"
NAMES = [
    "ISRG Root X1", "ISRG Root X2", "GTS Root R1", "GTS Root R3", "GTS Root R4",
    "DigiCert Global Root G2", "DigiCert Global Root G3",
    "DigiCert TLS RSA4096 Root G5", "DigiCert TLS ECC P384 Root G5",
    "Sectigo Public Server Authentication Root R46",
    "Sectigo Public Server Authentication Root E46",
    "Amazon Root CA 1", "Amazon Root CA 2", "Amazon Root CA 3", "Amazon Root CA 4",
]
ROOT = Path(__file__).resolve().parents[3]


def read_pinned(path, digest):
    path = Path(path).resolve()
    if path == ROOT or ROOT in path.parents:
        raise SystemExit("source inputs must remain outside the repository")
    data = path.read_bytes()
    if hashlib.sha256(data).hexdigest() != digest:
        raise SystemExit("pinned input hash mismatch: " + str(path))
    return data


def objects(data):
    out, obj = [], {}
    lines = iter(data.decode("utf-8").splitlines())
    for line in lines:
        if line.startswith("CKA_CLASS "):
            if obj:
                out.append(obj)
            obj = {}
        if not line.startswith("CKA_"):
            continue
        parts = line.split(" ", 2)
        key, kind = parts[:2]
        value = parts[2] if len(parts) == 3 else ""
        if kind == "MULTILINE_OCTAL":
            rows = []
            for row in lines:
                if row == "END":
                    break
                rows.append(row)
            else:
                raise SystemExit("unterminated octal attribute")
            value = bytes(int(v, 8) for v in re.findall(r"\\([0-7]{3})", "".join(rows)))
        else:
            value = value.strip('"')
        obj[key] = value
    if obj:
        out.append(obj)
    return out


def single(rows, name, kind):
    matches = [r for r in rows if r.get("CKA_LABEL") == name and r.get("CKA_CLASS") == kind]
    if len(matches) != 1:
        raise SystemExit("missing or ambiguous named input: " + name)
    return matches[0]


def generated(tag, version, source_hash, anchors):
    out = [
        "//go:build " + tag, "",
        "// Code generated by browser/gen_roots.py; DO NOT EDIT.",
        "// Production certificates/metadata: Mozilla NSS, MPL-2.0.",
        "// See ROOTS-SOURCES.txt and LICENSE.MPL-2.0.", "", "package tls", "",
        'const vendoredRootVersion = "' + version + '"',
        'const vendoredSourceHash = "' + source_hash + '"',
        "const gateRoots = " + ("true" if tag == "virelai_gate_roots" else "false"),
        "", "var vendoredRoots = []rootAnchor{",
    ]
    for name, der in anchors:
        out += [
            "\t{",
            '\t\tname: "' + name + '",',
            '\t\tsha256: "' + hashlib.sha256(der).hexdigest() + '",',
            "\t\tder: []byte{",
        ]
        for i in range(0, len(der), 16):
            out.append("\t\t\t" + ", ".join(f"0x{b:02x}" for b in der[i:i + 16]) + ",")
        out += ["\t\t},", "\t},"]
    return "\n".join(out + ["}", ""])


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_roots.py /outside/certdata.txt /outside/MPL-2.0.txt")
    source = read_pinned(sys.argv[1], SOURCE_HASH)
    notice = read_pinned(sys.argv[2], LICENSE_HASH)
    rows, anchors, inventory = objects(source), [], []
    for name in NAMES:
        cert = single(rows, name, "CKO_CERTIFICATE")
        trust = single(rows, name, "CKO_NSS_TRUST")
        der = cert["CKA_VALUE"]
        if trust.get("CKA_CERT_SHA1_HASH") != hashlib.sha1(der).digest():
            raise SystemExit("certificate/trust identity mismatch: " + name)
        if trust.get("CKA_TRUST_SERVER_AUTH") != "CKT_NSS_TRUSTED_DELEGATOR":
            raise SystemExit("named anchor lacks server-auth trust: " + name)
        if cert.get("CKA_NSS_SERVER_DISTRUST_AFTER") != "CK_FALSE":
            raise SystemExit("named anchor has a distrust date; owner review required: " + name)
        anchors.append((name, der))
        inventory.append(f"{name} | {len(der)} | {hashlib.sha256(der).hexdigest()} | "
                         "CKT_NSS_TRUSTED_DELEGATOR | CK_FALSE")
    if sum(len(der) for _, der in anchors) > 65536:
        raise SystemExit("DER input budget exceeded")
    # Pin the excluded record too, so a different source cannot silently erase
    # the owner ruling that reduced the original sixteen-anchor allowlist.
    r2 = single(rows, "GTS Root R2", "CKO_NSS_TRUST")
    if r2["CKA_TRUST_SERVER_AUTH"] != "CKT_NSS_MUST_VERIFY_TRUST":
        raise SystemExit("excluded R2 metadata changed; owner review required")
    fixture = (ROOT / "user/src/lib/tls/vectors/fx/root.der").read_bytes()
    dest = ROOT / "user/go/tls"
    (dest / "trust_root_gen.go").write_text(generated(
        "!virelai_gate_roots", "virelai-nss-15-" + REVISION[:12], SOURCE_HASH, anchors))
    (dest / "trust_gate_gen.go").write_text(generated(
        "virelai_gate_roots", "virelai-gate-roots-2026-09-14",
        hashlib.sha256(fixture).hexdigest(), [("AutoClaw Test Root CA", fixture)]))
    (dest / "LICENSE.MPL-2.0").write_bytes(notice)
    provenance = f"""M93f production trust inputs
Source: Mozilla NSS lib/ckfw/builtins/certdata.txt
Revision: {REVISION}
URL: https://raw.githubusercontent.com/nss-dev/nss/{REVISION}/lib/ckfw/builtins/certdata.txt
Complete source bytes: {len(source)}
Complete source SHA-256: {SOURCE_HASH}
License: MPL-2.0, primary certdata header; no NSS executable code adopted.
Notice URL: https://www.mozilla.org/media/MPL/2.0/index.txt
Notice SHA-256: {LICENSE_HASH}

Owner ruling on #1998, 2026-10-07, verbatim:
"Approve the 15-root set, excluding R2"
The original 16-anchor allowlist loses GTS Root R2 without replacement.
R2 DER SHA-256: 8d25cd97229dbf70356bda4eb3cc734031e24cf00fafcfd32dc76eb5841c7ea8
R2 server auth: CKT_NSS_MUST_VERIFY_TRUST; email: CKT_NSS_TRUSTED_DELEGATOR.
R2 is not a server-auth anchor. CK_FALSE distrust-after does not confer trust.
All included anchors have positive delegated server-auth trust and no server
distrust-after date. Never discard distrust metadata when updating this set.
Capacity remains 64; approved DER bytes total {sum(len(d) for _, d in anchors)}.

Name | DER bytes | DER SHA-256 | server-auth flag | server-distrust-after
""" + "\n".join(inventory) + f"""

Extraction: host-only browser/gen_roots.py, Python standard library.
Decode each MULTILINE_OCTAL attribute as octets, select exact CKA_LABEL/class,
join trust records by SHA-1 certificate identity, check delegated server-auth
and CK_FALSE server distrust-after, then emit original DER without conversion.
SHA-1 is NSS's record join, not certificate validation or a trust decision.
All inputs are hash-checked before any generated file is written.
Reproduce from the two pinned inputs kept OUTSIDE this repository:
  python3 user/go/browser/gen_roots.py /outside/certdata.txt /outside/MPL-2.0.txt
  gofmt -w user/go/tls/trust_root_gen.go user/go/tls/trust_gate_gen.go

Default !virelai_gate_roots: only the fifteen production anchors above.
Tag virelai_gate_roots: only AutoClaw, never any production anchor.
Fixture source: user/src/lib/tls/vectors/fx/root.der, repository LICENSE.
Fixture DER SHA-256: {hashlib.sha256(fixture).hexdigest()}
No runtime anchor injection, test-name exemption, trust override or downgrade.
"""
    (dest / "ROOTS-SOURCES.txt").write_text(provenance)
    print("Generated fifteen production anchors, one gate anchor, and notices.")


if __name__ == "__main__":
    main()
